# Generated by Django 6.0.1 on 2026-03-09 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板编码')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('title_template', models.CharField(max_length=255, verbose_name='标题模板')),
                ('content_template', models.TextField(verbose_name='内容模板')),
                ('sms_template_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='短信平台模板ID')),
            ],
            options={
                'verbose_name': '消息模板',
                'verbose_name_plural': '消息模板',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('success', '成功'), ('warning', '警告'), ('danger', '危险/异常')], default='info', max_length=20, verbose_name='级别')),
                ('notice_type', models.CharField(choices=[('status', '工单状态变更'), ('exception', '生产异常'), ('audit', '审核提醒'), ('system', '系统消息')], default='status', max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('target_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('sent_sms', models.BooleanField(default=False, verbose_name='是否同步发送短信')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='触发者')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
