# Generated by Django 6.0.1 on 2026-03-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notice_type',
            field=models.CharField(choices=[('status_change', '工单状态变更'), ('abnormal', '生产异常'), ('audit', '审核提醒'), ('system', '系统消息')], default='status', max_length=20, verbose_name='类型'),
        ),
    ]
