# Generated by Django 6.0.3 on 2026-04-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallaborrecord',
            old_name='procedure_type',
            new_name='procedure_key',
        ),
        migrations.RenameField(
            model_name='laborrecord',
            old_name='procedure_type',
            new_name='procedure_key',
        ),
    ]
