# Generated by Django 6.0.1 on 2026-02-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('kg', '千克 (kg)'), ('ton', '吨 (Ton)'), ('L', '升 (L)'), ('m3', '立方米 (m³)'), ('batch', '批/釜'), ('piece', '件/个')], default='kg', max_length=20, verbose_name='计量单位'),
        ),
    ]
