# Generated by Django 6.0.3 on 2026-03-11 11:38

import django.db.models.deletion
import production.models.partial.attachment
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='关联数据ID')),
                ('image', models.ImageField(help_text='支持上传生产现场、质检结果或异常情况的照片', upload_to=production.models.partial.attachment.attachment_upload_path, verbose_name='附件图片')),
                ('attachment_type', models.CharField(choices=[('QA', '质检/完工证明'), ('ABNORMAL', '异常/事故现场'), ('OTHER', '其他辅助说明')], default='OTHER', max_length=20, verbose_name='附件类型标签')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='出于化工合规与审计要求，附件不可物理删除。设为 True 仅在前端隐藏。', verbose_name='软删除标记')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联表类型')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '生产附件',
                'verbose_name_plural': '生产附件',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='production__content_527122_idx')],
            },
        ),
    ]
