# Generated by Django 6.0.3 on 2026-06-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_costconfig_price_and_more'),
        ('production', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvasynthesis',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送检时间'),
        ),
        migrations.AddField(
            model_name='cvcexport',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送检时间'),
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送检时间'),
        ),
        migrations.AddField(
            model_name='cvndistillation',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送检时间'),
        ),
        migrations.AddField(
            model_name='historicalcvasynthesis',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送检时间'),
        ),
        migrations.AddField(
            model_name='historicalcvcexport',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送检时间'),
        ),
        migrations.AddField(
            model_name='historicalcvcsynthesis',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送检时间'),
        ),
        migrations.AddField(
            model_name='historicalcvndistillation',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送检时间'),
        ),
        migrations.AlterField(
            model_name='cvasynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvasynthesis',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related_workshop', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.AlterField(
            model_name='cvcexport',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvcexport',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related_workshop', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.AlterField(
            model_name='cvcsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvcsynthesis',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related_workshop', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.AlterField(
            model_name='cvndistillation',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvndistillation',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related_workshop', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related_workshop', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.AlterField(
            model_name='historicalcvasynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='historicalcvasynthesis',
            name='workshop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.AlterField(
            model_name='historicalcvcexport',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='historicalcvcexport',
            name='workshop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.AlterField(
            model_name='historicalcvcsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='historicalcvcsynthesis',
            name='workshop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.AlterField(
            model_name='historicalcvndistillation',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='historicalcvndistillation',
            name='workshop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.AlterField(
            model_name='historicalcvnsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='historicalcvnsynthesis',
            name='workshop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.AlterField(
            model_name='historicallaborrecord',
            name='cost_config',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category__contains': ['labor']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.costconfig', verbose_name='工种/费用项'),
        ),
        migrations.AlterField(
            model_name='laborrecord',
            name='cost_config',
            field=models.ForeignKey(limit_choices_to={'category__contains': ['labor']}, on_delete=django.db.models.deletion.PROTECT, to='inventory.costconfig', verbose_name='工种/费用项'),
        ),
    ]
