# Generated by Django 6.0.1 on 2026-03-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvasynthesis',
            name='status',
            field=models.CharField(choices=[('new', '待产/新建'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvcexport',
            name='status',
            field=models.CharField(choices=[('new', '待产/新建'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvcsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '待产/新建'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvndistillation',
            name='status',
            field=models.CharField(choices=[('new', '待产/新建'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '待产/新建'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
    ]
