# Generated by Django 6.0.1 on 2026-02-03 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_inventory_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kettle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 101, 2-05, R-01', max_length=50, unique=True, verbose_name='釜皿编号')),
                ('workshop', models.CharField(blank=True, help_text='例: 一车间, 二车间', max_length=50, verbose_name='所属车间')),
                ('capacity', models.FloatField(default=0, help_text='单位: 升', verbose_name='标准容积 (L)')),
                ('supported_processes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cvn_syn', 'CVN 合成'), ('cvn_dist', 'CVN 精馏'), ('cva_syn', 'CVA 合成'), ('cvc_syn', 'CVC 合成'), ('cvc_dist', 'CVC 精馏')], max_length=20), blank=True, default=list, help_text='该设备能做哪些工艺 (可多选)', verbose_name='适用工艺')),
                ('status', models.CharField(choices=[('idle', '🟢 空闲 (可使用)'), ('running', '🔴 生产中'), ('to_clean', '🟡 待清洁'), ('maintenance', '⚪ 维护/故障')], default='idle', max_length=20, verbose_name='当前状态')),
                ('current_batch_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='当前占用批次')),
            ],
            options={
                'verbose_name': '釜皿/设备',
                'verbose_name_plural': '釜皿/设备管理',
                'ordering': ['workshop', 'name'],
            },
        ),
    ]
