# Generated by Django 6.0.1 on 2026-03-10 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_cvasynthesis_status_alter_cvcexport_status_and_more'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvndistillation',
            name='workshop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cvn_distillation', to='system.workshop', verbose_name='工单所属车间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvnsynthesis',
            name='workshop',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='cvn_synthesis', to='system.workshop', verbose_name='工单所属车间'),
            preserve_default=False,
        ),
    ]
