# Generated by Django 6.0.3 on 2026-03-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_historicalcvasynthesis_historicalcvasynthesisinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvasynthesis',
            name='pre_content_adn',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-ADN含量%'),
        ),
        migrations.AddField(
            model_name='cvasynthesis',
            name='pre_content_cvn',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-CVN含量%'),
        ),
        migrations.AddField(
            model_name='cvasynthesis',
            name='pre_content_dcb',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-DCB含量%'),
        ),
        migrations.AddField(
            model_name='cvcexport',
            name='pre_content_cva',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-CVA含量%'),
        ),
        migrations.AddField(
            model_name='cvcexport',
            name='pre_content_cvc',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-CVC含量%'),
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='pre_content_cva',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-CVA含量%'),
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='pre_content_cvn',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-CVN残留%'),
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='pre_content_water',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-水分%'),
        ),
        migrations.AddField(
            model_name='historicalcvasynthesis',
            name='pre_content_adn',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-ADN含量%'),
        ),
        migrations.AddField(
            model_name='historicalcvasynthesis',
            name='pre_content_cvn',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-CVN含量%'),
        ),
        migrations.AddField(
            model_name='historicalcvasynthesis',
            name='pre_content_dcb',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-DCB含量%'),
        ),
        migrations.AddField(
            model_name='historicalcvcexport',
            name='pre_content_cva',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-CVA含量%'),
        ),
        migrations.AddField(
            model_name='historicalcvcexport',
            name='pre_content_cvc',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-CVC含量%'),
        ),
        migrations.AddField(
            model_name='historicalcvcsynthesis',
            name='pre_content_cva',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-CVA含量%'),
        ),
        migrations.AddField(
            model_name='historicalcvcsynthesis',
            name='pre_content_cvn',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-CVN残留%'),
        ),
        migrations.AddField(
            model_name='historicalcvcsynthesis',
            name='pre_content_water',
            field=models.FloatField(blank=True, null=True, verbose_name='精前-水分%'),
        ),
    ]
