# Generated by Django 6.0.3 on 2026-06-12 07:15

import django.db.models.deletion
import simple_history.models
import xiangheChemical.utils.time_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_cvasynthesis_test_time_cvcexport_test_time_and_more'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVNStripping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='生产批号')),
                ('status', models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(default=xiangheChemical.utils.time_utils.get_default_start_time, verbose_name='开始时间')),
                ('expected_time', models.DateTimeField(default=xiangheChemical.utils.time_utils.get_default_expected_time, verbose_name='预计完成时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('test_time', models.DateTimeField(blank=True, null=True, verbose_name='送检时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('version', models.IntegerField(default=0, help_text='用于乐观锁并发控制，每次修改都会加1', verbose_name='工单版本号')),
                ('input_total_cvn_weight', models.FloatField(default=0, help_text='应等于来源明细重量之和', verbose_name='CVN合成粗品重量(kg)')),
                ('pre_content_cvn', models.FloatField(blank=True, null=True, verbose_name='合成液-CVN含量%')),
                ('pre_content_dcb', models.FloatField(blank=True, null=True, verbose_name='合成液-DCB含量%')),
                ('pre_content_adn', models.FloatField(blank=True, null=True, verbose_name='合成液-ADN含量%')),
                ('cvn_str_crude_weight', models.FloatField(blank=True, null=True, verbose_name='CVN粗蒸粗品重量(kg)')),
                ('recycled_dcb', models.FloatField(blank=True, null=True, verbose_name='回收DCB重量(kg)')),
                ('output_content_cvn', models.FloatField(blank=True, null=True, verbose_name='粗蒸-CVN含量%')),
                ('output_content_dcb', models.FloatField(blank=True, null=True, verbose_name='粗蒸-DCB含量%')),
                ('output_content_adn', models.FloatField(blank=True, null=True, verbose_name='粗蒸-ADN含量%')),
                ('kettle', models.ForeignKey(blank=True, help_text='该生产步骤所使用的具体釜皿/设备', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='production.kettle', verbose_name='生产设备')),
                ('operator', models.ForeignKey(help_text='自动关联当前登录账号，不可为空', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='记录员')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related_workshop', to='system.workshop', verbose_name='所属车间')),
            ],
            options={
                'verbose_name': '1.5-CVN粗蒸',
                'verbose_name_plural': '1.5-CVN粗蒸',
                'ordering': ['-start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVNStrippingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_weight', models.FloatField(default=0, verbose_name='投入重量(kg)')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumed_in_stripping', to='production.cvnsynthesis', verbose_name='来源合成批次')),
                ('stripping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='production.cvnstripping', verbose_name='所属粗蒸工单')),
            ],
            options={
                'verbose_name': 'CVN粗蒸投料明细',
                'verbose_name_plural': 'CVN粗蒸投料明细',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCVNStripping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('batch_no', models.CharField(db_index=True, max_length=50, verbose_name='生产批号')),
                ('status', models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('pending_qc', '待质检'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(default=xiangheChemical.utils.time_utils.get_default_start_time, verbose_name='开始时间')),
                ('expected_time', models.DateTimeField(default=xiangheChemical.utils.time_utils.get_default_expected_time, verbose_name='预计完成时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('test_time', models.DateTimeField(blank=True, null=True, verbose_name='送检时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='最后更新')),
                ('version', models.IntegerField(default=0, help_text='用于乐观锁并发控制，每次修改都会加1', verbose_name='工单版本号')),
                ('input_total_cvn_weight', models.FloatField(default=0, help_text='应等于来源明细重量之和', verbose_name='CVN合成粗品重量(kg)')),
                ('pre_content_cvn', models.FloatField(blank=True, null=True, verbose_name='合成液-CVN含量%')),
                ('pre_content_dcb', models.FloatField(blank=True, null=True, verbose_name='合成液-DCB含量%')),
                ('pre_content_adn', models.FloatField(blank=True, null=True, verbose_name='合成液-ADN含量%')),
                ('cvn_str_crude_weight', models.FloatField(blank=True, null=True, verbose_name='CVN粗蒸粗品重量(kg)')),
                ('recycled_dcb', models.FloatField(blank=True, null=True, verbose_name='回收DCB重量(kg)')),
                ('output_content_cvn', models.FloatField(blank=True, null=True, verbose_name='粗蒸-CVN含量%')),
                ('output_content_dcb', models.FloatField(blank=True, null=True, verbose_name='粗蒸-DCB含量%')),
                ('output_content_adn', models.FloatField(blank=True, null=True, verbose_name='粗蒸-ADN含量%')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kettle', models.ForeignKey(blank=True, db_constraint=False, help_text='该生产步骤所使用的具体釜皿/设备', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.kettle', verbose_name='生产设备')),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, help_text='自动关联当前登录账号，不可为空', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='记录员')),
                ('workshop', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.workshop', verbose_name='所属车间')),
            ],
            options={
                'verbose_name': 'historical 1.5-CVN粗蒸',
                'verbose_name_plural': 'historical 1.5-CVN粗蒸',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCVNStrippingInput',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('use_weight', models.FloatField(default=0, verbose_name='投入重量(kg)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.cvnsynthesis', verbose_name='来源合成批次')),
                ('stripping', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.cvnstripping', verbose_name='所属粗蒸工单')),
            ],
            options={
                'verbose_name': 'historical CVN粗蒸投料明细',
                'verbose_name_plural': 'historical CVN粗蒸投料明细',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
