# Generated by Django 6.0.3 on 2026-03-12 03:32

import django.db.models.deletion
import production.models.partial.attachment
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_attachment_is_deleted_attachment_change_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='change_at',
        ),
        migrations.AddField(
            model_name='attachment',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='系统自动生成的WebP极速加载图', null=True, upload_to=production.models.partial.attachment.thumbnail_upload_path, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('QA', '质检/完工证明'), ('ABNORMAL', '异常/事故现场'), ('OTHER', '其他辅助说明'), ('INVALID', '已废弃/错图')], default='OTHER', max_length=20, verbose_name='附件类型标签'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_attachments', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(help_text='支持上传生产现场、质检结果或异常情况的照片', upload_to=production.models.partial.attachment.attachment_upload_path, verbose_name='附件原图'),
        ),
    ]
