# Generated by Django 6.0.1 on 2026-03-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_cvndistillation_workshop_cvnsynthesis_workshop'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvasynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvcexport',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvcsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvndistillation',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvndistillation',
            name='workshop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='cvn_distillation', to='system.workshop', verbose_name='工单所属车间'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='workshop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cvn_synthesis', to='system.workshop', verbose_name='工单所属车间'),
        ),
    ]
