# Generated by Django 6.0.1 on 2026-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_kettle'),
    ]

    operations = [
        migrations.AddField(
            model_name='kettle',
            name='last_process',
            field=models.CharField(blank=True, choices=[('cvn_syn', 'CVN 合成'), ('cvn_dist', 'CVN 精馏'), ('cva_syn', 'CVA 合成'), ('cvc_syn', 'CVC 合成'), ('cvc_dist', 'CVC 精馏')], help_text='记录该设备上一次生产的工艺类型，用于判断连投或交叉污染风险', max_length=20, null=True, verbose_name='上批工艺'),
        ),
        migrations.AddField(
            model_name='kettle',
            name='last_product_name',
            field=models.CharField(blank=True, help_text='记录上一次生产的具体产品名称或代码', max_length=100, null=True, verbose_name='上批产品名称'),
        ),
    ]
