# Generated by Django 6.0.3 on 2026-03-24 01:47

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_costconfiglog_options'),
        ('production', '0003_cvasynthesis_pre_content_adn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvasynthesis',
            name='labor_records',
        ),
        migrations.RemoveField(
            model_name='cvcexport',
            name='labor_records',
        ),
        migrations.RemoveField(
            model_name='cvcsynthesis',
            name='labor_records',
        ),
        migrations.RemoveField(
            model_name='cvndistillation',
            name='labor_records',
        ),
        migrations.RemoveField(
            model_name='cvnsynthesis',
            name='labor_records',
        ),
        migrations.RemoveField(
            model_name='historicalcvasynthesis',
            name='labor_records',
        ),
        migrations.RemoveField(
            model_name='historicalcvcexport',
            name='labor_records',
        ),
        migrations.RemoveField(
            model_name='historicalcvcsynthesis',
            name='labor_records',
        ),
        migrations.RemoveField(
            model_name='historicalcvndistillation',
            name='labor_records',
        ),
        migrations.RemoveField(
            model_name='historicalcvnsynthesis',
            name='labor_records',
        ),
        migrations.CreateModel(
            name='HistoricalLaborRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('batch_no', models.CharField(db_index=True, help_text='关联具体工单的批号，用于钻取明细', max_length=21, verbose_name='生产批号')),
                ('procedure_type', models.CharField(db_index=True, help_text='工艺标识（如 CVN_SYN, CVN_DIS），极大地提升按工艺分类的报表查询性能', max_length=7, verbose_name='工艺类别')),
                ('worker_count', models.PositiveIntegerField(default=1, verbose_name='投入人数')),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='投入工时')),
                ('cost_snapshot', models.DecimalField(decimal_places=2, help_text='保存操作当时的单价，防止全局调价破坏历史财务数据', max_digits=10, verbose_name='单价快照(元)')),
                ('record_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='用于时间序列报表统计的核心字段', verbose_name='记录日期')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cost_config', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'labor'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.costconfig', verbose_name='工种/费用项')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 人力投入记录',
                'verbose_name_plural': 'historical 人力投入记录',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LaborRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(db_index=True, help_text='关联具体工单的批号，用于钻取明细', max_length=21, verbose_name='生产批号')),
                ('procedure_type', models.CharField(db_index=True, help_text='工艺标识（如 CVN_SYN, CVN_DIS），极大地提升按工艺分类的报表查询性能', max_length=7, verbose_name='工艺类别')),
                ('worker_count', models.PositiveIntegerField(default=1, verbose_name='投入人数')),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='投入工时')),
                ('cost_snapshot', models.DecimalField(decimal_places=2, help_text='保存操作当时的单价，防止全局调价破坏历史财务数据', max_digits=10, verbose_name='单价快照(元)')),
                ('record_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='用于时间序列报表统计的核心字段', verbose_name='记录日期')),
                ('cost_config', models.ForeignKey(limit_choices_to={'category': 'labor'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.costconfig', verbose_name='工种/费用项')),
            ],
            options={
                'verbose_name': '人力投入记录',
                'verbose_name_plural': '人力投入记录',
                'ordering': ['-record_date', '-id'],
            },
        ),
    ]
