# Generated by Django 6.0.3 on 2026-06-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_cvnstripping_cvnstrippinginput_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvndistillation',
            options={'ordering': ['-start_time'], 'verbose_name': '3-CVN精馏', 'verbose_name_plural': '3-CVN精馏'},
        ),
        migrations.AlterModelOptions(
            name='cvnstripping',
            options={'ordering': ['-start_time'], 'verbose_name': '2-CVN粗蒸', 'verbose_name_plural': '2-CVN粗蒸'},
        ),
        migrations.AlterModelOptions(
            name='historicalcvndistillation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 3-CVN精馏', 'verbose_name_plural': 'historical 3-CVN精馏'},
        ),
        migrations.AlterModelOptions(
            name='historicalcvnstripping',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 2-CVN粗蒸', 'verbose_name_plural': 'historical 2-CVN粗蒸'},
        ),
        migrations.AddField(
            model_name='cvnstripping',
            name='recycled_dcb_purity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='粗蒸工序回收DCB纯度%'),
        ),
        migrations.AddField(
            model_name='historicalcvnstripping',
            name='recycled_dcb_purity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='粗蒸工序回收DCB纯度%'),
        ),
        migrations.AlterField(
            model_name='cvnstripping',
            name='input_total_cvn_weight',
            field=models.FloatField(default=0, help_text='应等于来源明细重量之和', verbose_name='CVN合成液重量(kg)'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='cvn_syn_crude_weight',
            field=models.FloatField(blank=True, default=0, help_text='人工称重', null=True, verbose_name='产出-CVN合成液重量(kg)'),
        ),
        migrations.AlterField(
            model_name='historicalcvnstripping',
            name='input_total_cvn_weight',
            field=models.FloatField(default=0, help_text='应等于来源明细重量之和', verbose_name='CVN合成液重量(kg)'),
        ),
        migrations.AlterField(
            model_name='historicalcvnsynthesis',
            name='cvn_syn_crude_weight',
            field=models.FloatField(blank=True, default=0, help_text='人工称重', null=True, verbose_name='产出-CVN合成液重量(kg)'),
        ),
    ]
