# Generated by Django 6.0.3 on 2026-06-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_cvndistillation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvnsynthesis',
            name='recovered_dcb_amount',
        ),
        migrations.RemoveField(
            model_name='cvnsynthesis',
            name='recovered_dcb_purity',
        ),
        migrations.RemoveField(
            model_name='historicalcvnsynthesis',
            name='recovered_dcb_amount',
        ),
        migrations.RemoveField(
            model_name='historicalcvnsynthesis',
            name='recovered_dcb_purity',
        ),
        migrations.AddField(
            model_name='cvnstripping',
            name='consumed_weight',
            field=models.FloatField(default=0, editable=False, help_text='系统自动更新，不可手改', verbose_name='已领用重量(kg)'),
        ),
        migrations.AddField(
            model_name='historicalcvnstripping',
            name='consumed_weight',
            field=models.FloatField(default=0, editable=False, help_text='系统自动更新，不可手改', verbose_name='已领用重量(kg)'),
        ),
        migrations.AlterField(
            model_name='cvndistillationinput',
            name='source_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumed_in_distillation', to='production.cvnstripping', verbose_name='粗品来源批次'),
        ),
        migrations.AlterField(
            model_name='cvnstripping',
            name='recycled_dcb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='回收DCB重量(kg)'),
        ),
        migrations.AlterField(
            model_name='historicalcvndistillationinput',
            name='source_batch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.cvnstripping', verbose_name='粗品来源批次'),
        ),
        migrations.AlterField(
            model_name='historicalcvnstripping',
            name='recycled_dcb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='回收DCB重量(kg)'),
        ),
    ]
