# Generated by Django 6.0.3 on 2026-03-11 08:42

import django.utils.timezone
import production.models.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_cvasynthesis_status_alter_cvcexport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvasynthesis',
            name='expected_time',
            field=models.DateTimeField(default=production.models.core.BaseProductionStep.get_default_expected_time, verbose_name='预计完成时间'),
        ),
        migrations.AddField(
            model_name='cvasynthesis',
            name='version',
            field=models.IntegerField(default=0, help_text='用于乐观锁并发控制，每次修改都会加1', verbose_name='工单版本号'),
        ),
        migrations.AddField(
            model_name='cvcexport',
            name='expected_time',
            field=models.DateTimeField(default=production.models.core.BaseProductionStep.get_default_expected_time, verbose_name='预计完成时间'),
        ),
        migrations.AddField(
            model_name='cvcexport',
            name='version',
            field=models.IntegerField(default=0, help_text='用于乐观锁并发控制，每次修改都会加1', verbose_name='工单版本号'),
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='expected_time',
            field=models.DateTimeField(default=production.models.core.BaseProductionStep.get_default_expected_time, verbose_name='预计完成时间'),
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='version',
            field=models.IntegerField(default=0, help_text='用于乐观锁并发控制，每次修改都会加1', verbose_name='工单版本号'),
        ),
        migrations.AddField(
            model_name='cvndistillation',
            name='expected_time',
            field=models.DateTimeField(default=production.models.core.BaseProductionStep.get_default_expected_time, verbose_name='预计完成时间'),
        ),
        migrations.AddField(
            model_name='cvndistillation',
            name='version',
            field=models.IntegerField(default=0, help_text='用于乐观锁并发控制，每次修改都会加1', verbose_name='工单版本号'),
        ),
        migrations.AddField(
            model_name='cvnsynthesis',
            name='expected_time',
            field=models.DateTimeField(default=production.models.core.BaseProductionStep.get_default_expected_time, verbose_name='预计完成时间'),
        ),
        migrations.AddField(
            model_name='cvnsynthesis',
            name='version',
            field=models.IntegerField(default=0, help_text='用于乐观锁并发控制，每次修改都会加1', verbose_name='工单版本号'),
        ),
        migrations.AlterField(
            model_name='cvasynthesis',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='cvasynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvcexport',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='cvcexport',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvcsynthesis',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='cvcsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvndistillation',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='cvndistillation',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新工单'), ('running', '生产中'), ('delayed', '已延迟'), ('abnormal', '异常单'), ('cancel', '已取消'), ('completed', '已完成')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
    ]
