# Generated by Django 6.0.3 on 2026-03-13 04:07

import xiangheChemical.utils.time_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_attachment_change_at_attachment_changed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvasynthesis',
            old_name='input_total_weight',
            new_name='input_total_cvc_dis_weight',
        ),
        migrations.RenameField(
            model_name='cvcexport',
            old_name='product_content_cva',
            new_name='content_cva',
        ),
        migrations.RenameField(
            model_name='cvcexport',
            old_name='product_content_cvc',
            new_name='content_cvc',
        ),
        migrations.RenameField(
            model_name='cvcexport',
            old_name='premium_weight',
            new_name='crude_weight',
        ),
        migrations.RenameField(
            model_name='cvcexport',
            old_name='input_total_weight',
            new_name='input_total_cvc_weight',
        ),
        migrations.RenameField(
            model_name='cvcsynthesis',
            old_name='product_weight',
            new_name='crude_weight',
        ),
        migrations.RenameField(
            model_name='cvndistillation',
            old_name='output_weight',
            new_name='crude_weight',
        ),
        migrations.RenameField(
            model_name='cvndistillation',
            old_name='input_total_weight',
            new_name='input_total_cvn_weight',
        ),
        migrations.RenameField(
            model_name='cvndistillation',
            old_name='output_adn_content',
            new_name='output_content_adn',
        ),
        migrations.RenameField(
            model_name='cvndistillation',
            old_name='output_cvn_content',
            new_name='output_content_cvn',
        ),
        migrations.RenameField(
            model_name='cvndistillation',
            old_name='output_dcb_content',
            new_name='output_content_dcb',
        ),
        migrations.RenameField(
            model_name='cvndistillation',
            old_name='pre_adn_content',
            new_name='pre_content_adn',
        ),
        migrations.RenameField(
            model_name='cvndistillation',
            old_name='pre_cvn_content',
            new_name='pre_content_cvn',
        ),
        migrations.RenameField(
            model_name='cvndistillation',
            old_name='pre_dcb_content',
            new_name='pre_content_dcb',
        ),
        migrations.RemoveField(
            model_name='cvcsynthesis',
            name='product_content',
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='content_cva',
            field=models.FloatField(blank=True, help_text='CVC合成工艺中CVA的纯度', null=True, verbose_name='成品-CVA含量%'),
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='content_cvc',
            field=models.FloatField(blank=True, help_text='CVC合成的纯度', null=True, verbose_name='成品-CVC含量%'),
        ),
        migrations.AlterField(
            model_name='cvasynthesis',
            name='start_time',
            field=models.DateTimeField(default=xiangheChemical.utils.time_utils.get_default_start_time, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='cvcexport',
            name='start_time',
            field=models.DateTimeField(default=xiangheChemical.utils.time_utils.get_default_start_time, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='cvcsynthesis',
            name='start_time',
            field=models.DateTimeField(default=xiangheChemical.utils.time_utils.get_default_start_time, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='cvndistillation',
            name='start_time',
            field=models.DateTimeField(default=xiangheChemical.utils.time_utils.get_default_start_time, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='start_time',
            field=models.DateTimeField(default=xiangheChemical.utils.time_utils.get_default_start_time, verbose_name='开始时间'),
        ),
    ]
