# Generated by Django 6.0.3 on 2026-03-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_cvasynthesis_labor_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallaborrecord',
            name='procedure_type',
            field=models.CharField(db_index=True, help_text='工艺标识（如 CVN_SYN, CVN_DIS），极大地提升按工艺分类的报表查询性能', max_length=17, verbose_name='工艺类别'),
        ),
        migrations.AlterField(
            model_name='laborrecord',
            name='procedure_type',
            field=models.CharField(db_index=True, help_text='工艺标识（如 CVN_SYN, CVN_DIS），极大地提升按工艺分类的报表查询性能', max_length=17, verbose_name='工艺类别'),
        ),
    ]
