# Generated by Django 6.0.1 on 2026-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_kettle_last_process_kettle_last_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kettle',
            name='current_level',
            field=models.FloatField(default=0, help_text='当前釜内物料总量，用于计算负载率', verbose_name='当前投入量'),
        ),
        migrations.AlterField(
            model_name='kettle',
            name='capacity',
            field=models.FloatField(default=0, help_text='单位: 升', verbose_name='最大容积 (L)'),
        ),
    ]
