# Generated by Django 6.0.3 on 2026-03-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_historicallaborrecord_procedure_type_and_more'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvasynthesis',
            name='workshop',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='cva_synthesis', to='system.workshop', verbose_name='工单所属车间'),
        ),
        migrations.AddField(
            model_name='cvcexport',
            name='workshop',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='cvc_export', to='system.workshop', verbose_name='工单所属车间'),
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='workshop',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='cvc_synthesis', to='system.workshop', verbose_name='工单所属车间'),
        ),
        migrations.AddField(
            model_name='historicalcvasynthesis',
            name='workshop',
            field=models.ForeignKey(blank=True, db_constraint=False, default=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.workshop', verbose_name='工单所属车间'),
        ),
        migrations.AddField(
            model_name='historicalcvcexport',
            name='workshop',
            field=models.ForeignKey(blank=True, db_constraint=False, default=5, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.workshop', verbose_name='工单所属车间'),
        ),
        migrations.AddField(
            model_name='historicalcvcsynthesis',
            name='workshop',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.workshop', verbose_name='工单所属车间'),
        ),
    ]
