# Generated by Django 6.0.3 on 2026-03-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_rename_input_total_weight_cvasynthesis_input_total_cvc_dis_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvnsynthesis',
            old_name='input_recycled_dcb',
            new_name='recycled_dcb',
        ),
    ]
