# Generated by Django 6.0.3 on 2026-06-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_cvnsynthesis_recovered_dcb_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvasynthesis',
            old_name='input_total_cvc_dis_weight',
            new_name='input_total_cvn_dis_weight',
        ),
        migrations.RenameField(
            model_name='historicalcvasynthesis',
            old_name='input_total_cvc_dis_weight',
            new_name='input_total_cvn_dis_weight',
        ),
    ]
