# Generated by Django 6.0.1 on 2026-02-04 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_kettle_current_level_alter_kettle_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvasynthesis',
            name='kettles',
        ),
        migrations.RemoveField(
            model_name='cvcexport',
            name='kettles',
        ),
        migrations.RemoveField(
            model_name='cvcsynthesis',
            name='kettles',
        ),
        migrations.RemoveField(
            model_name='cvndistillation',
            name='kettles',
        ),
        migrations.RemoveField(
            model_name='cvnsynthesis',
            name='kettles',
        ),
        migrations.AddField(
            model_name='cvasynthesis',
            name='kettle',
            field=models.ForeignKey(blank=True, help_text='该生产步骤所使用的具体釜皿/设备', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='production.kettle', verbose_name='生产设备'),
        ),
        migrations.AddField(
            model_name='cvcexport',
            name='kettle',
            field=models.ForeignKey(blank=True, help_text='该生产步骤所使用的具体釜皿/设备', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='production.kettle', verbose_name='生产设备'),
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='kettle',
            field=models.ForeignKey(blank=True, help_text='该生产步骤所使用的具体釜皿/设备', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='production.kettle', verbose_name='生产设备'),
        ),
        migrations.AddField(
            model_name='cvndistillation',
            name='kettle',
            field=models.ForeignKey(blank=True, help_text='该生产步骤所使用的具体釜皿/设备', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='production.kettle', verbose_name='生产设备'),
        ),
        migrations.AddField(
            model_name='cvnsynthesis',
            name='kettle',
            field=models.ForeignKey(blank=True, help_text='该生产步骤所使用的具体釜皿/设备', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='production.kettle', verbose_name='生产设备'),
        ),
    ]
