# Generated by Django 6.0.3 on 2026-03-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_rename_input_recycled_dcb_cvnsynthesis_recycled_dcb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvasynthesis',
            old_name='crude_weight',
            new_name='cva_crude_weight',
        ),
        migrations.RenameField(
            model_name='cvcexport',
            old_name='crude_weight',
            new_name='cvc_dis_crude_weight',
        ),
        migrations.RenameField(
            model_name='cvcsynthesis',
            old_name='crude_weight',
            new_name='cvc_syn_crude_weight',
        ),
        migrations.RenameField(
            model_name='cvndistillation',
            old_name='crude_weight',
            new_name='cvn_dis_crude_weight',
        ),
        migrations.RenameField(
            model_name='cvnsynthesis',
            old_name='crude_weight',
            new_name='cvn_syn_crude_weight',
        ),
    ]
