# Generated by Django 6.0.1 on 2026-02-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_cvasynthesis_kettles_remove_cvcexport_kettles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvasynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新建/待投 (New)'), ('running', '生产中 (Running)'), ('completed', '已完工 (Completed)')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='cvcexport',
            name='status',
            field=models.CharField(choices=[('new', '新建/待投 (New)'), ('running', '生产中 (Running)'), ('completed', '已完工 (Completed)')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='cvcsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新建/待投 (New)'), ('running', '生产中 (Running)'), ('completed', '已完工 (Completed)')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='cvndistillation',
            name='status',
            field=models.CharField(choices=[('new', '新建/待投 (New)'), ('running', '生产中 (Running)'), ('completed', '已完工 (Completed)')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='cvnsynthesis',
            name='status',
            field=models.CharField(choices=[('new', '新建/待投 (New)'), ('running', '生产中 (Running)'), ('completed', '已完工 (Completed)')], db_index=True, default='new', help_text='生产状态流转：新建 -> 生产中(锁原料) -> 完工(入成品)', max_length=20, verbose_name='状态'),
        ),
    ]
