# Generated by Django 6.0.1 on 2026-02-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_cvasynthesis_status_cvcexport_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvasynthesis',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='cvcexport',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='cvcsynthesis',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='cvndistillation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
    ]
