# Generated by Django 6.0.1 on 2026-02-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_cvasynthesis_end_time_alter_cvcexport_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='crude_weight',
            field=models.FloatField(blank=True, default=0, help_text='物理称重', null=True, verbose_name='产出-CVN粗品重量(kg)'),
        ),
    ]
