# Generated by Django 6.0.1 on 2026-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_cvnsynthesis_crude_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='recovered_dcb_amount',
            field=models.FloatField(blank=True, default=0, help_text='单位：升', null=True, verbose_name='回收-DCB数量(L)'),
        ),
    ]
