# Generated by Django 6.0.1 on 2026-02-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_cvnsynthesis_recovered_dcb_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='waste_batches',
            field=models.IntegerField(blank=True, default=0, help_text='填整数，用于计算排污费', null=True, verbose_name='破氰废水处理(批次/釜)'),
        ),
    ]
