# Generated by Django 6.0.1 on 2026-02-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_alter_cvnsynthesis_waste_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvnsynthesis',
            name='input_recycled_dcb',
            field=models.FloatField(blank=True, default=0, help_text='套用回收溶剂', null=True, verbose_name='投入-回收二氯丁烷(kg/L)'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='raw_alkali',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='投入-液碱(kg)'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='raw_dcb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='投入-二氯丁烷(kg)'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='raw_nacn',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='投入-氰化钠(kg)'),
        ),
        migrations.AlterField(
            model_name='cvnsynthesis',
            name='raw_tbab',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='投入-TBAB(kg)'),
        ),
    ]
