# Generated by Django 6.0.3 on 2026-03-26 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='配置代码')),
                ('label', models.CharField(max_length=50, verbose_name='配置项名称')),
                ('category', models.CharField(choices=[('material', '原料成本'), ('labor', '人工成本'), ('waste', '环保/排污成本'), ('product', '产品/产值')], max_length=20, verbose_name='费用类别')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价/金额 (元)')),
                ('unit', models.CharField(choices=[('kg', '千克 (kg)'), ('ton', '吨 (Ton)'), ('L', '升 (L)'), ('m3', '立方米 (m³)'), ('batch', '批/釜'), ('hour', '小时 (Hour)')], default='kg', max_length=20, verbose_name='计价单位')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近更新')),
            ],
            options={
                'verbose_name': '费用/价格配置',
                'verbose_name_plural': '费用/价格配置',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('kg', '千克 (kg)'), ('ton', '吨 (Ton)'), ('L', '升 (L)'), ('m3', '立方米 (m³)'), ('batch', '批/釜'), ('piece', '件/个')], default='kg', max_length=20, verbose_name='计量单位')),
                ('key', models.CharField(help_text='程序调用唯一标识，如 raw_dcb', max_length=50, unique=True, verbose_name='物料代码')),
                ('name', models.CharField(max_length=50, verbose_name='物料名称')),
                ('category', models.CharField(choices=[('raw', '原材料'), ('intermediate', '中间品'), ('product', '成品')], default='raw', max_length=20, verbose_name='分类')),
                ('quantity', models.FloatField(default=0, verbose_name='当前库存')),
                ('safe_stock', models.FloatField(default=0, help_text='低于此数值时标红预警', verbose_name='安全库存预警线')),
            ],
            options={
                'verbose_name': '库存清单',
                'verbose_name_plural': '库存清单',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CostConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价格')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新价格')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.costconfig', verbose_name='关联配置项')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '价格变更记录',
                'verbose_name_plural': '价格变更记录',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('purchase', '购入/入库'), ('sale', '销售/出库'), ('correction', '盘点/修正'), ('production', '生产消耗/产出'), ('safe_stock', '预警线调整')], max_length=20, verbose_name='操作类型')),
                ('change_amount', models.FloatField(verbose_name='变动数量(+/-)')),
                ('quantity_after', models.FloatField(verbose_name='变动后余量(快照)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注/原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='关联物料')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '库存变动日志',
                'verbose_name_plural': '库存变动日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
