# Generated by Django 6.0.3 on 2026-05-30 00:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costconfig',
            name='price',
        ),
        migrations.RemoveField(
            model_name='costconfiglog',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='costconfiglog',
            name='old_price',
        ),
        migrations.AddField(
            model_name='costconfig',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本指导价 (元)'),
        ),
        migrations.AddField(
            model_name='costconfig',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='销售/产值单价 (元)'),
        ),
        migrations.AddField(
            model_name='costconfiglog',
            name='new_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='新成本价'),
        ),
        migrations.AddField(
            model_name='costconfiglog',
            name='new_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='新销售价'),
        ),
        migrations.AddField(
            model_name='costconfiglog',
            name='old_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='原成本价'),
        ),
        migrations.AddField(
            model_name='costconfiglog',
            name='old_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='原销售价'),
        ),
        migrations.AlterField(
            model_name='costconfig',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('material', '原料成本'), ('labor', '人工成本'), ('waste', '环保/排污成本'), ('product', '产品/产值')], max_length=20), blank=True, default=list, verbose_name='费用类别'),
        ),
    ]
