# Generated by Django 6.0.1 on 2026-03-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costconfiglog',
            options={'ordering': ['-changed_at'], 'verbose_name': '价格变更记录', 'verbose_name_plural': '价格变更记录'},
        ),
    ]
